/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0wHWAp4VreI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import SendEmail from "./SendEmail"
import Subscribe from "./Subscribe"

export function Component2() {
  return (
    <div className="flex flex-col min-h-screen"> 
      <header className="flex items-center h-16 px-4 lg:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="#">
            <SunriseIcon className="h-6 w-6" />
            <span className="font-bold">Acme</span>
          </Link>
        </div>
        <nav className="ml-auto hidden sm:flex items-center gap-4">
          <Link className="font-medium underline underline-offset-2" href="#">
            Home
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Services
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Portfolio
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="grid w-full gap-4 px-4 py-10 md:gap-6 md:py-16 lg:py-20">
        <div className="container grid items-center gap-4 px-4 text-center md:gap-10 md:px-6">
          <div className="space-y-3">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Welcome to Acme Inc</h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We're a team of passionate individuals dedicated to delivering excellence.
            </p>
          </div>
          {/* <div className="mx-auto w-full max-w-[600px]">
            <form className="flex w-full max-w-sm mx-auto items-center gap-2">
              <Input placeholder="Enter your email" required type="email" />
              <Button type="submit">Subscribe</Button>
            </form>
            <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">Sign up to receive updates. No spam.</p>
          </div> */}
          <Subscribe />
        </div>
        <div className="mx-auto w-full max-w-6xl grid gap-4 px-4 md:gap-10 md:px-6">
          <img
            alt="Hero"
            className="rounded-lg object-cover overflow-hidden aspect-[3/1] mx-auto"
            height="400"
            src="/ninja.jpg"
            width="1200"
          />
        </div>
        <div className="mx-auto w-full max-w-6xl grid gap-4 px-4 md:gap-10 md:px-6">
          <div className="grid gap-4">
            <div className="grid gap-2">
              <h2 className="text-2xl font-bold tracking-tight">Our Mission Statement</h2>
              <p className="text-gray-500 dark:text-gray-400">
                To empower businesses with innovative solutions that drive growth and success.
              </p>
            </div>
            <div className="grid gap-2">
              <h2 className="text-2xl font-bold tracking-tight">Our Core Values</h2>
              <ul className="grid gap-2 list-disc list-outside">
                <li>Customer Centricity</li>
                <li>Innovation</li>
                <li>Integrity</li>
                <li>Collaboration</li>
                <li>Continuous Improvement</li>
              </ul>
            </div>
          </div>
        </div>
        {/* <div className="container grid items-center place-items-center pt-10 gap-4 px-4 md:px-6">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Welcome to Acme Inc</h1>
          <form className="mx-auto max-w-sm space-y-4 pt-10 lg:order-last lg:mx-0">
            <div className="grid grid-cols-2 gap-4">
              <Input className="w-full" placeholder="Name" type="text" />
              <Input className="w-full" placeholder="Email" type="email" />
            </div>
            <Input className="min-h-[150px] w-full" placeholder="Message" type="text" />
            <Button className="w-full lg:w-auto" type="submit">
              Contact Us
            </Button>
          </form>
        </div> */}
        <SendEmail />
      </main>
      <footer className="flex flex-col shrink-0 py-10 w-full items-center justify-center gap-2 text-sm md:flex-row md:gap-4 md:py-6 lg:gap-2 lg:text-base">
        <div className="flex items-center gap-2 md:order-1">
          <Link
            className="flex h-6 w-6 items-center justify-center rounded-md bg-gray-900 shadow hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-50 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="#"
          >
            <span className="sr-only">Twitter</span>
            <TwitterIcon className="h-4 w-4 fill-white" />
          </Link>
          <Link
            className="flex h-6 w-6 items-center justify-center rounded-md bg-gray-900 shadow hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-50 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="#"
          >
            <span className="sr-only">Facebook</span>
            <FacebookIcon className="h-4 w-4 fill-white" />
          </Link>
          <Link
            className="flex h-6 w-6 items-center justify-center rounded-md bg-gray-900 shadow hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-50 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
            href="#"
          >
            <span className="sr-only">LinkedIn</span>
            <LinkedinIcon className="h-4 w-4 fill-white" />
          </Link>
        </div>
        <div className="flex items-center justify-center md:order-3">
          <nav className="flex space-x-4">
            <Link className="hover:underline" href="#">
              Terms
            </Link>
            <Link className="hover:underline" href="#">
              Privacy
            </Link>
            <Link className="hover:underline" href="#">
              Policy
            </Link>
          </nav>
        </div>
        <div className="order-2 text-xs text-center text-gray-500 md:order-3 md:text-gray-500 dark:text-gray-400 md:text-gray-500/60">
          © 2023 Acme Inc. All rights reserved.
        </div>
      </footer>
    </div>
  )
}

function FacebookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function LinkedinIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}

function SunriseIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v8" />
      <path d="m4.93 10.93 1.41 1.41" />
      <path d="M2 18h2" />
      <path d="M20 18h2" />
      <path d="m19.07 10.93-1.41 1.41" />
      <path d="M22 22H2" />
      <path d="m8 6 4-4 4 4" />
      <path d="M16 18a4 4 0 0 0-8 0" />
    </svg>
  )
}

