/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kixZ53BueDs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Cabin } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

cabin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component1() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="flex items-center h-16 px-4 lg:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="#">
            <SunriseIcon className="h-6 w-6" />
            <span className="font-bold">Acme</span>
          </Link>
        </div>
        <nav className="ml-auto hidden lg:flex items-center gap-4">
          <Link className="font-medium underline underline-offset-2" href="#">
            Home
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Services
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Portfolio
          </Link>
          <Link className="font-medium underline underline-offset-2" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 flex flex-col items-center py-12 lg:py-24">
        <div className="container grid items-center gap-4 px-4 md:px-6">
          <div className="space-y-3 text-center lg:space-y-4 lg:text-left">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">We build beautiful websites</h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We are a team of experienced web designers and developers who create stunning and user-friendly websites
              for businesses of all sizes.
            </p>
          </div>
          <form className="mx-auto max-w-sm space-y-4 lg:order-last lg:mx-0">
            <div className="grid grid-cols-2 gap-4">
              <Input className="w-full" placeholder="Name" type="text" />
              <Input className="w-full" placeholder="Email" type="email" />
            </div>
            <Input className="min-h-[150px] w-full" placeholder="Message" type="text" />
            <Button className="w-full lg:w-auto" type="submit">
              Contact Us
            </Button>
          </form>
        </div>
      </main>
    </div>
  )
}

function SunriseIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v8" />
      <path d="m4.93 10.93 1.41 1.41" />
      <path d="M2 18h2" />
      <path d="M20 18h2" />
      <path d="m19.07 10.93-1.41 1.41" />
      <path d="M22 22H2" />
      <path d="m8 6 4-4 4 4" />
      <path d="M16 18a4 4 0 0 0-8 0" />
    </svg>
  )
}
